### ISSUE TITLE
Incompatibility with firefox 57.0

### ISSUE THREAD

**Issue by foreveryone1** [xxdavid/lastfm-friends-who-listen#8] opened 2017-11-14 23:12 UTC
Because of the new WebExtension framework this extension is broken.

**Comment by xxdavid** [comment] 2017-11-15 20:33
Duplicate of #7.

**Comment by xxdavid** [comment] 2017-11-15 20:35
Hi, thank you for informing. I have looked into that and it looks like Firefox doesn't like `jQuery.ajax` (I don't know why), I'll have to change it to use something more modern like `fetch`.

**Comment by xxdavid** [comment] 2017-11-15 21:20
Aha, so the whole problem was with the API undeclared in the manifest…

**Comment by xxdavid** [comment] 2017-11-15 21:20
I'm gonna package it and upload to the store for review.

**Comment by xxdavid** [comment] 2017-11-15 21:46
Horray, the add-on has been approved!
I think it will update automatically, otherwise you can download it from [here](https://addons.mozilla.org/cs/firefox/addon/friends-who-listen/).

**Closed as completed by xxdavid** 2017-11-15 21:46 UTC

**Comment by foreveryone1** [comment] 2017-11-15 22:36
Thank you for your time David, I appreciate it!
